/** @type {import('tailwindcss').Config} */
export default {
        darkMode: "class",
        content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
          extend: {
            "colors": {
                "on-primary-fixed": "#022113",
                "on-tertiary-fixed-variant": "#2c4e36",
                "surface-bright": "#f8faf9",
                "on-tertiary-container": "#ffffff",
                "tertiary-fixed": "#c5eccc",
                "on-error": "#ffffff",
                "surface-tint": "#476554",
                "on-secondary-fixed-variant": "#3a4951",
                "primary-container": "#5e7d6b",
                "on-background": "#191c1c",
                "inverse-surface": "#2e3131",
                "secondary-fixed": "#d5e5ef",
                "outline-variant": "#c2c8c2",
                "surface-variant": "#e1e3e2",
                "surface-container": "#eceeed",
                "on-tertiary-fixed": "#00210e",
                "outline": "#727973",
                "tertiary": "#42654c",
                "inverse-primary": "#adceb9",
                "on-tertiary": "#ffffff",
                "surface-container-high": "#e6e9e8",
                "on-error-container": "#93000a",
                "secondary-fixed-dim": "#b9c9d3",
                "tertiary-container": "#5b7e63",
                "on-surface-variant": "#424844",
                "secondary": "#516169",
                "error": "#ba1a1a",
                "on-secondary-fixed": "#0e1d25",
                "on-secondary-container": "#55656d",
                "secondary-container": "#d2e2ec",
                "primary": "#466453",
                "surface-container-lowest": "#ffffff",
                "primary-fixed-dim": "#adceb9",
                "error-container": "#ffdad6",
                "inverse-on-surface": "#eff1f0",
                "primary-fixed": "#c9ebd5",
                "on-secondary": "#ffffff",
                "surface-container-low": "#f2f4f3",
                "on-surface": "#191c1c",
                "tertiary-fixed-dim": "#aad0b1",
                "surface-dim": "#d8dada",
                "on-primary-container": "#ffffff",
                "on-primary-fixed-variant": "#2f4d3d",
                "background": "#f8faf9",
                "surface-container-highest": "#e1e3e2",
                "surface": "#f8faf9",
                "on-primary": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "stack-md": "16px",
                "touch-target-min": "48px",
                "stack-sm": "8px",
                "stack-lg": "32px",
                "gutter": "16px",
                "container-margin": "24px",
                "unit": "8px"
            },
            "fontFamily": {
                "body-lg": ["Public Sans"],
                "headline-md": ["Public Sans"],
                "label-bold": ["Public Sans"],
                "display-xl": ["Public Sans"],
                "label-sm": ["Public Sans"],
                "headline-lg": ["Public Sans"],
                "body-md": ["Public Sans"]
            },
            "fontSize": {
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "label-bold": ["14px", {"lineHeight": "20px", "fontWeight": "700"}],
                "display-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
            }
          },
        },
      }